_target_: src.models.autoencoder_module.AutoEncoderModule

use_ema: False
ema_beta: 0.9999
ema_power: 0.7
sample_rate: 16000
loss_type: mse

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas : [0.95, 0.999]
  eps: 1e-6
  weight_decay: 1e-3
  
scheduler: null
  
autoencoder:
  _target_: src.models.components.backbones.autoencoder.AutoEncoder1d
  in_channels: 1
  channels: 32
  resnet_groups: 8
  multipliers: [1, 2, 4, 8, 8, 8, 1]
  factors: [2, 2, 2, 1, 1, 1]
  num_blocks: [2, 2, 8, 8, 8, 8]

bottleneck:
  - _target_: src.models.components.backbones.bottleneck.TanhBottleneck
  - _target_: src.models.components.backbones.bottleneck.NoiserBottleneck
    sigma: 0.2
      
