_target_: src.models.vqgan_module.VQGANModule

use_ema: False
ema_beta: 0.9999
ema_power: 0.7
sample_rate: 16000
apply_grad_penalty: False
accum_grads: 4
discr_multi_scales: [1, 0.5, 0.25]

optimizer_gener:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas : [0.95, 0.999]
  eps: 1e-6
  weight_decay: 1e-3
  
optimizer_discr:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  betas : [0.95, 0.999]
  eps: 1e-6
  weight_decay: 1e-3
  
scheduler: null
  
autoencoder:
  _target_: src.models.components.backbones.autoencoder1d.VQAutoEncoder1d
  
vqdiscriminator:
  _target_: src.models.components.backbones.rvqautoencoder.MultiScaleDiscriminator
  
vqstftdiscriminator:
  _target_: src.models.components.backbones.rvqautoencoder.ComplexSTFTDiscriminator

bottleneck:
  _target_: src.models.components.backbones.bottleneck.VQBottleneck
  dim: 512
  codebook_size: 1024
      
