_target_: src.datamodules.dcaseDev_complex_datamodule.DcaseDevDataModule
data_dir: ${paths.data_dir}/DCASEFoleySoundSynthesisDevSet
batch_size: 4
num_workers: 8
pin_memory: False
spec_factor: 0.3
spec_abs_exponent: 0.5
hop_length: 128
num_frames: 128
n_fft: 510
